-- begin NONRDA_REFERENCE_DATA
alter table NONRDA_REFERENCE_DATA add constraint FK_NONRDA_REFERENCE_DATA_ON_PARENT foreign key (PARENT_ID) references NONRDA_REFERENCE_DATA(ID)^
create index IDX_NONRDA_REFERENCE_DATA_ON_PARENT on NONRDA_REFERENCE_DATA (PARENT_ID)^

-- end NONRDA_REFERENCE_DATA
