alter table CARES_INCIDENT_REPORT add constraint FK_CARES_INCIDENT_REPORT_ON_STATUS foreign key (STATUS_ID) references NONRDA_REFERENCE_DATA(ID);
create index IDX_CARES_INCIDENT_REPORT_ON_STATUS on CARES_INCIDENT_REPORT (STATUS_ID);
