alter table CARES_ALLEGATION_PERPETRATOR_LINK add constraint FK_ALLPER_ON_ALLEGATION foreign key (ALLEGATION_ID) references CARES_ALLEGATION(ID);
alter table CARES_ALLEGATION_PERPETRATOR_LINK add constraint FK_ALLPER_ON_PERPETRATOR foreign key (PERPETRATOR_ID) references CARES_PERSON(ID);
