alter table CARES_INCIDENT_REPORT add constraint FK_CARES_INCIDENT_REPORT_ON_CONTACT_METHOD foreign key (CONTACT_METHOD_ID) references NONRDA_REFERENCE_DATA(ID);
alter table CARES_INCIDENT_REPORT add constraint FK_CARES_INCIDENT_REPORT_ON_REPORTER foreign key (REPORTER_ID) references CARES_PERSON(ID);
create index IDX_CARES_INCIDENT_REPORT_ON_CONTACT_METHOD on CARES_INCIDENT_REPORT (CONTACT_METHOD_ID);
create index IDX_CARES_INCIDENT_REPORT_ON_REPORTER on CARES_INCIDENT_REPORT (REPORTER_ID);
